[project]
name = "lab-tictactoe1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "argparse",
    "fastapi>=0.116.1",
    "httpx>=0.28.1",
    "redis>=6.2.0",
    "uvicorn>=0.35.0",
    "websockets>=15.0.1",
]
